- name: include secret.yml
  include_vars: ../vars/secret.yml

- name: Install MySQL and dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - mysql-server
    - mysql-client
    - python3-mysqldb
    - libmysqlclient-dev
  become: yes

- name: Start and enable MySQL service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Set MySQL root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ db_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  become: yes

- name: Enable remote login to MySQL
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
  notify:
    - Restart mysql
  become: yes